services:
  fastapi:
    build:
      context: ./backend
    container_name: fastapi-ad-campaign-manager-app
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    command: uvicorn app.presentation.api.v1.main:app --host 0.0.0.0 --port 8000 --reload
