
name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/python-ci.yml'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip 
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint application code with Pylint
        run: |
          # Only lint the main application code, exclude tests directory
          pylint app

      - name: Test with Pytest
        run: |
          # Pytest should automatically find pytest.ini and the tests directory
          pytest
        env:
          DATABASE_URL: "sqlite:///:memory:"
          AUTH_SECRET_KEY: "test-ci-secret-key-12345"
          AUTH_ALGORITHM: "HS256"
          ACCESS_TOKEN_EXPIRE_MINUTES: "5"
          FIRST_SUPERUSER_EMAIL: "ci-admin@test.com"
          FIRST_SUPERUSER_PASSWORD: "ci-superpassword"
          BACKEND_CORS_ORIGINS: '["*"]'